server:
  port: 8080

spring:
  application:
    name: chat-setting

  ai:
    openai:
      api-key: ${DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max

http:
  client:
    connect-timeout: 60s
    read-timeout: 60s